apiVersion: batch/v1
kind: Job
metadata:
  name: countdown
  annotations:
    consolekind: ConsoleYAMLSample
    consolename: countdown-job-sample
    consoledesc: Sample To run a job
    consoletitle: Sample To run a job
spec:
    template:
      metadata:
        name: countdown
      spec:
        containers:
          - name: counter
            image: centos:7
            command:
              - "bin/bash"
              - "-c"
              - "for i in 9 8 7 6 5 4 3 2 1 ; do echo $i ; done"
        restartPolicy: Never
