[[constraint]]
  name = "github.com/googleapis/gnostic"
  version = "v0.2.0"

[[override]]
  source = "https://github.com/fsnotify/fsnotify.git"
  name = "gopkg.in/fsnotify.v1"

[[constraint]]
  name = "github.com/openshift/api"
  branch = "release-4.3"

[[constraint]]
  name = "github.com/openshift/client-go"
  branch = "release-4.3"

[[constraint]]
  name = "sigs.k8s.io/controller-runtime"
  version = "v0.4.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.16.2"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.16.2"

[prune]
  go-tests = true
  unused-packages = true
