[[constraint]]
  name = "github.com/googleapis/gnostic"
  version = "v0.2.0"

[[constraint]]
  name = "sigs.k8s.io/controller-runtime"
  # 0.2.0-beta.2 latest @dev time
  version = "0.2.0-beta.2"

[[constraint]]
  name = "k8s.io/client-go"
  # req'd by controller-runtime latest (v0.2.-beta.2)
  version = "kubernetes-1.14.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  # req'd by controller-runtime latest (v0.2.-beta.2)
  version = "kubernetes-1.14.1"

[prune]
  go-tests = true
  unused-packages = true