[[constraint]]
  name = "golang.org/x/text"
  version = "0.3.0"


[[override]]
  name = "k8s.io/client-go"
  # revision for tag "kubernetes-1.13.1"
  revision = "8d9ed539ba3134352c586810e749e58df4e94e4f"

[[override]]
  name = "github.com/coreos/prometheus-operator"
  version = "=v0.26.0"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  version = "=v0.1.10"



[[constraint]]
  name = "k8s.io/client-go"
  # revision for tag "kubernetes-1.12.3"
  revision = "8d9ed539ba3134352c586810e749e58df4e94e4f"

[prune]
  go-tests = true
  unused-packages = true
