[[constraint]]
  name = "github.com/googleapis/gnostic"
  version = "v0.2.0"

[[constraint]]
  name = "sigs.k8s.io/controller-runtime"
  version = "v0.1.10"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.1"

[prune]
  go-tests = true
  unused-packages = true