[[constraint]]
  name = "github.com/googleapis/gnostic"
  version = "v0.2.0"

[[constraint]]
  name = "github.com/openshift/api"
  branch = "release-4.3"

[[constraint]]
  name = "github.com/openshift/client-go"
  branch = "release-4.3"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.16.2"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.16.2"

[prune]
  go-tests = true
  unused-packages = true
