apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: example
spec:
  backgroundColor: '#0088ce'
  color: '#fff'
  link:
    href: 'https://www.example.com'
    text: Optional link text
  location: BannerTop
  text: This is an example notification message with an optional link.